name: edge_connectivity_pk
description: A Flutter package for managing edge connectivity features.
version: 0.0.1
homepage: https://github.com/Sabarish-iOS/edge_connectivity_pk
repository: https://github.com/Sabarish-iOS/edge_connectivity_pk
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true